; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs=w55rp20

[env]
framework = arduino
lib_deps =
  arduino-libraries/ArduinoHttpClient @ 0.4.0
  bblanchon/ArduinoJson @ 6.19.4
  arduino-libraries/NTPClient @ 3.2.1
monitor_speed = 115200

[env:m5stack-fire]
platform = espressif32
board = m5stack-fire
lib_deps =
 m5stack/M5Unified @ ^0.2.2
 ${env.lib_deps}
  ; https://github.com/m5stack/M5Stack
  ; https://github.com/lovyan03/LovyanGFX.git
build_flags = -D M5_MODE -D USE_WIFI
monitor_speed = ${env.monitor_speed}
; upload_speed = 115200
; upload_port = COM7
; board_build.partitions = no_ota.csv
; upload_protocol = 
; upload_port 

[env:picow]
platform = raspberrypi
board = rpipicow
platform_packages =
    framework-arduinopico@https://github.com/earlephilhower/arduino-pico.git#4.4.1
lib_deps =
  https://github.com/lovyan03/LovyanGFX.git
 ${env.lib_deps}
build_flags = -D PICO_MODE -D USE_WIFI

[env:w55rp20]
platform = raspberrypi
; board = pico
board = wiznet_55rp20_evb_pico
; board_build.core = earlephilhower
platform_packages =
    framework-arduinopico@https://github.com/earlephilhower/arduino-pico.git#4.4.1
#upload_protocol = picotool
lib_deps =
  ; https://github.com/katsumin/Ethernet_Generic
  ; lovyan03/LovyanGFX @ 0.4.17
  ; https://github.com/katsumin/LovyanGFX.git
  https://github.com/lovyan03/LovyanGFX.git
 ${env.lib_deps}
build_flags = -D PICO_MODE -D 
; build_flags = -Wl,-Map,output.map -D _ETG_LOGLEVEL_=3 -D USING_CUSTOM_SPI

monitor_speed = ${env.monitor_speed}
; debug_tool = raspberrypi-swd
; upload_protocol = blackmagic
; debug_port = COM5
; upload_port = COM5
; monitor_port = COM5
; debug_tool = blackmagic
