; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = raspberrypi
framework = arduino

[env:pico]
; board = pico
board = wiznet_55rp20_evb_pico
; board_build.core = earlephilhower
platform_packages =
    framework-arduinopico@https://github.com/earlephilhower/arduino-pico.git#4.4.1
#upload_protocol = picotool
lib_deps =
  https://github.com/katsumin/Ethernet_Generic
  ; lovyan03/LovyanGFX @ 0.4.17
  ; https://github.com/katsumin/LovyanGFX.git
  https://github.com/lovyan03/LovyanGFX.git
  openslab-osu/SSLClient @ 1.6.11
  arduino-libraries/ArduinoHttpClient @ 0.4.0
  bblanchon/ArduinoJson @ 6.19.4
  arduino-libraries/NTPClient @ 3.2.1
; build_flags = -Wl,-Map,output.map -D _ETG_LOGLEVEL_=3 -D USING_CUSTOM_SPI

monitor_speed = 115200
; debug_tool = raspberrypi-swd
; upload_protocol = blackmagic
; debug_port = COM5
; upload_port = COM5
; monitor_port = COM5
; debug_tool = blackmagic
